name: Android Build

on:
  push:
    branches:
      - android16kb
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: â˜• Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ› Debug xkr krypto
        run: npm ls kryptokrona-crypto

      - name: ğŸ©¹ Patch NPM packages
        run: npm run patch

      - name: ğŸ”§ Patch keypear for Node 18
        run: |
          KEYPEAR_PKG="node_modules/keypear/package.json"
          echo "Patching keypear imports..."
          jq '.imports.fs = {"bare":"builtin:fs","default":"fs"} | .imports.path = {"bare":"builtin:path","default":"path"}' $KEYPEAR_PKG > $KEYPEAR_PKG.tmp
          mv $KEYPEAR_PKG.tmp $KEYPEAR_PKG

      - name: ğŸ“‹ Get offline lists
        run: npm run get-offline-lists

      - name: ğŸ”‘ Export private keys file
        run: npm run create-private-keys

      - name: ğŸ“¦ Bundle bare
        run: ./bin/bundle.js -ra

      - name: ğŸ” Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore

      - name: ğŸ” Export signing vars
        run: |
          echo "ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: ğŸ› ï¸ Build Release APK & AAB
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: ğŸ“¤ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: ğŸ“¤ Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
